version: '3.8'

services:
  # FastAPI主应用服务
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-vector-search
    ports:
      - "8000:8000"
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=True
      - WORKERS=4
      - MILVUS_COLLECTION_NAME=questions
      - RATE_LIMIT=100/minute
    depends_on:
      - milvus-standalone
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - milvus-network

  # Milvus数据库服务
  milvus-standalone:
    image: milvusdb/milvus:v2.2.8
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus-data:/var/lib/milvus
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      - milvus-network

  # Milvus依赖：etcd
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.5
    container_name: milvus-etcd
    command: ["etcd", "--advertise-client-urls=http://127.0.0.1:2379", "--listen-client-urls=http://0.0.0.0:2379"]
    volumes:
      - etcd-data:/etcd
    networks:
      - milvus-network

  # Milvus依赖：MinIO
  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    container_name: milvus-minio
    command: ["minio", "server", "/minio-data"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/minio-data
    networks:
      - milvus-network

  # Prometheus监控服务（可选）
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - milvus-network
    depends_on:
      - fastapi-service

  # Grafana可视化服务（可选）
  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - milvus-network
    depends_on:
      - prometheus

networks:
  milvus-network:
    driver: bridge

volumes:
  milvus-data:
  etcd-data:
  minio-data:
  prometheus-data:
  grafana-data: